name = "samvidhx-tracker"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "TRACKER_KV"
id = "dadcb7d0323642fb862e28c0cc1c1531"
preview_id = "680e84db51be45db98b465d73f5c559e"